[versions]
compileSdk = "36"
targetSdk = "36"
minSdk = "23"
jdk = "17"
kotlin = "2.3.10"
ksp = "2.3.2"
agp = "9.0.0"
gms = "4.4.4"
crashlytics = "3.0.6"
compose = "1.10.1"
coroutines = "1.10.2"
sqlDelight = "2.2.1"
room = "2.8.4"
androidxSqlite = "2.6.2"
saferoom = "1.4.0"
androidSqlCipher = "4.13.0"
iosSqlCipher = "4.9.0"
jdbcSQLite = "3.51.2.0"
koin-bom = "4.1.1"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1"
kotlinx-browser = "0.5.0"
kermit = "2.0.8"
materialThemePrefs = "0.9.8"
composeMaterial3 = "1.9.0"
composeMaterialIconsExtended = "1.7.3"
composeMaterialAdaptive = "1.2.0"
androidxAppcompat = "1.7.1"
androidxViewModel = "2.9.6"
androidxNavigation = "2.9.2"
androidxActivityCompose = "1.12.3"
androidxComposeTest = "1.10.2"
androidxCoreSplashscreen = "1.2.0"
androidxTracing = "1.3.0"
androidxLifecycle = "2.10.0"
androidxArch = "2.2.0"
androidxPaging = "3.4.0"
androidxTestExt = "1.3.0"
androidxTest = "1.7.0"
androidxTestOrchestrator = "1.6.1"
firebase = "34.9.0"
leakCanary = "2.14"
junit = "4.13.2"
mockito = "5.21.0"
turbine = "1.2.1"
espresso = "3.7.0"
desugar = "2.1.5"
androidSecurityLint = "1.0.4"
appdirs = "1.5.0"
uiTooling = "1.10.2"
download = "5.7.0"
okio = "3.16.4"
accompanist-permissions = "0.37.3"

[libraries]
coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }

sqlDelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqlDelight-web = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "sqlDelight" }
#sqlDelight-paging = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "sqlDelight" } #TODO use instead of ":thirdparty:app:cash:sqldelight:paging3" when the lib will dependent of "androidx.paging" instead of "app.cash.paging"
sqlDelight-coroutinesExt = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-asyncExt = { module = "app.cash.sqldelight:async-extensions", version.ref = "sqlDelight" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "androidxSqlite" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidxSqlite" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidxSqlite" }

commonsware-saferoom = { module = "io.github.softartdev:saferoom.x", version.ref = "saferoom" }
android-sqlcipher = { module = "net.zetetic:sqlcipher-android", version.ref = "androidSqlCipher" }
sqlite-jdbc = { module = "io.github.willena:sqlite-jdbc", version.ref = "jdbcSQLite" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-test = { module = "io.insert-koin:koin-test" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-crashlytics = { module = "co.touchlab:kermit-crashlytics", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }

material-theme-prefs = { module = "io.github.softartdev:theme-material3", version.ref = "materialThemePrefs" }

compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeMaterialIconsExtended" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "compose" }

compose-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "composeMaterialAdaptive" }
compose-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "composeMaterialAdaptive" }
compose-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "composeMaterialAdaptive" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "androidxComposeTest" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidxComposeTest" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxViewModel" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxViewModel" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "androidxTracing" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }

androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidxLifecycle" }

androidx-arch-core-common = { module = "androidx.arch.core:core-common", version.ref = "androidxArch" }
androidx-arch-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "androidxArch" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidxArch" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidxPaging" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidxPaging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidxPaging" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTestOrchestrator" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

leakCanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
leakCanary-android-process = { module = "com.squareup.leakcanary:leakcanary-android-process", version.ref = "leakCanary" }
leakCanary-plumber-android = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakCanary" }
leakCanary-android-instrumentation = { module = "com.squareup.leakcanary:leakcanary-android-instrumentation", version.ref = "leakCanary" }

junit = { module = "junit:junit", version.ref = "junit" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version = "5.2.0" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espresso-device = { module = "androidx.test.espresso:espresso-device", version = "1.1.0" }
espresso-idling-resource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }

desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

android-security-lint = { module = "com.android.security.lint:lint", version.ref = "androidSecurityLint" }

[plugins]
gradle-convention = { id = "com.softartdev.notedelight.buildlogic.convention", version = "unspecified" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
room = { id = "androidx.room", version.ref = "room" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
download = { id = "de.undercouch.download", version.ref = "download" }

[bundles]
mockito = ["mockito-core", "mockito-inline"]
androidx-sqlite = ["androidx-sqlite", "androidx-sqlite-ktx", "androidx-sqlite-framework"]
androidx-arch-core = ["androidx-arch-core-common", "androidx-arch-core-runtime"]
androidx-test = ["androidx-test-rules", "androidx-test-runner"]
espresso = ["espresso-core", "espresso-contrib"]
