[versions]
compileSdk = "34"
targetSdk = "34"
minSdk = "21"
jdk = "17"
kotlin = "2.0.0"
agp = "8.4.2"
gms = "4.4.2"
crashlytics = "3.0.1"
compose = "1.6.11"
composeCompiler = "1.5.14"
coroutines = "1.8.1"
sqlDelight = "2.0.2"
androidxSqlite = "2.4.0"
saferoom = "1.3.0"
androidSqlCipher = "4.5.4"
iosSqlCipher = "4.5.4"
sqlcipherKtnPod = "1.4.2"
decompose = "2.2.2-compose-experimental"
koin = "3.5.3"
kotlinx-serialization = "1.6.3"
kotlinx-datetime = "0.6.0"
napier = "2.7.1"
mokoResources = "0.24.0"
materialThemePrefs = "0.8.3"
androidxActivityCompose = "1.9.0"
androidxComposeTest = "1.6.7"
androidxCoreSplashscreen = "1.0.1"
androidxLegacySupport = "1.0.0"
androidxPreference = "1.2.1"
androidxMultidex = "2.0.1"
androidxTracing = "1.2.0"
androidxLifecycle = "2.8.2"
androidxArch = "2.2.0"
androidxTestExt = "1.1.5"
androidxTest = "1.5.2"
androidxTestOrchestrator = "1.4.2"
googleAndroidMaterial = "1.12.0"
firebase = "33.1.0"
leakCanary = "2.14"
junit = "4.13.2"
mockito = "5.11.0"
turbine = "1.1.0"
espresso = "3.5.1"
desugar = "2.0.4"
appdirs = "1.2.2"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

sqlDelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-coroutinesExt = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

stately-common = { module = "co.touchlab:stately-common", version = "2.0.6" } #FIXME https://github.com/cashapp/sqldelight/issues/4357

androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "androidxSqlite" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidxSqlite" }

commonsware-saferoom = { module = "com.commonsware.cwac:saferoom.x", version.ref = "saferoom" }

android-sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "androidSqlCipher" }

sqlcipherKtnPod = { module = "io.github.softartdev:sqlcipher-ktn-pod", version.ref = "sqlcipherKtnPod" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extComposeJb = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-jvm = { module = "io.insert-koin:koin-core-jvm", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

napier = { module = "io.github.aakira:napier", version.ref = "napier" }

mokoResources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResources" }
mokoResources = { module = "dev.icerock.moko:resources", version.ref = "mokoResources" }
mokoResources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "mokoResources" }
mokoResources-test = { module = "dev.icerock.moko:resources-test", version.ref = "mokoResources" }

material-theme-prefs = { module = "io.github.softartdev:theme-material3", version.ref = "materialThemePrefs" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidxComposeTest" }

androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-legacy-support = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidxLegacySupport" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidxPreference" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidxMultidex" }
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "androidxTracing" }

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

androidx-arch-core-common = { module = "androidx.arch.core:core-common", version.ref = "androidxArch" }
androidx-arch-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "androidxArch" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidxArch" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTestOrchestrator" }

google-android-material = { module = "com.google.android.material:material", version.ref = "googleAndroidMaterial" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

leakCanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
leakCanary-android-process = { module = "com.squareup.leakcanary:leakcanary-android-process", version.ref = "leakCanary" }
leakCanary-plumber-android = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakCanary" }
leakCanary-android-instrumentation = { module = "com.squareup.leakcanary:leakcanary-android-instrumentation", version.ref = "leakCanary" }

junit = { module = "junit:junit", version.ref = "junit" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version = "5.2.0" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espresso-device = { module = "androidx.test.espresso:espresso-device", version = "1.0.0-rc01" }
espresso-idling-resource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }

desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

[plugins]
gradle-convention = { id = "com.softartdev.notedelight.buildlogic.convention", version = "unspecified" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
mokoResources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "mokoResources" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }

[bundles]
mockito = ["mockito-core", "mockito-inline"]
androidx-sqlite = ["androidx-sqlite", "androidx-sqlite-ktx", "androidx-sqlite-framework"]
androidx-arch-core = ["androidx-arch-core-common", "androidx-arch-core-runtime"]
androidx-test = ["androidx-test-rules", "androidx-test-runner"]
espresso = ["espresso-core", "espresso-contrib"]